### ISSUE TITLE
Generalize wave generators to handle custom bit-depth

### ISSUE THREAD

**Issue by tekkac** [cienicera/cairo-wave#10]
**ODHack**
---
- Go to the [Nicera Labs OD Telegram](https://t.me/niceralabs)
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Description**
---
Generalize all wave generators in `utils.cairo` with a custom bit_depth parameter so that they handle a custom bit-depth.
Must handle at least: 4-bit, 8-bit (current), 16-bit, 24-bit

[Wiki Resource on bit-depth](https://en.wikipedia.org/wiki/Audio_bit_depth)

**Additional Information**
---------------------------
[Medium Difficulty  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] Implement custom bit-depth 
- [ ] Write and pass unit tests
- [ ] Generate example files

**Comment by silent-cipher** [comment]
Hii @tekkac , I have went through the code and thought of handling this issue. If it's fine I would like to tackle this issue.
