### ISSUE TITLE
Generate or encode a lo-fi sound pack drum kit

### ISSUE THREAD

**Issue by tekkac** [cienicera/cairo-wave#14]
**Contributing**
---
- Go to the [Nicera Labs OD Telegram](https://t.me/niceralabs)
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Description**
---

Find a way to encode a lo-fi drum kit sound pack.

- The drum kit should contain a snare, a bass, a kick and hi-hat. 
- Due to Starknet limitations, the WAV file should be encoded in 4 or 8-bit mono with ~8kHz sample rate.

(Online drum kits are usually encoded with a too high sample rate)

**Additional Information**
---------------------------
[High Difficulty  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] Implement a drum kit.
- [ ] Write and pass unit tests
- [ ] Generate example files

**Comment by MPSxDev** [comment]
I am very interested in taking on this issue. I have been studying Cairo hard, completing the last bootcamp, speedrunstark, starlings and developing quests in nodeguardians. I am also a musician and have worked with samples, I know the whole audio part. This project will be a great challenge that will unite my 2 passions. 
I am an active member of the coding dojo and I am immediately available to start working on this issue.
