### ISSUE TITLE
Convert to Cairo 2.6.0 

### ISSUE THREAD

**Issue by tekkac** [cienicera/cairo-wave#15]
**ODHack Process**
--- 

- Go to the [Nicera Labs OD Telegram](https://t.me/niceralabs)
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Description**
---
Update the library to the latest version of Cairo.

**Additional Information**
---------------------------
[Low Difficulty  - Cairo - Low Priority]

**Acceptance Criteria**
---

- [ ] Update the repo
- [ ] The test should be passing.

**Comment by JimmyFate** [comment]
Hey, I could give this a try :)

**Comment by Oshioke-Salaki** [comment]
Please can I handle this?

**Comment by tekkac** [comment]
Please join the Telegram in the description so we can have a quick chat about it.
