### ISSUE TITLE
Implement sine wave generator

### ISSUE THREAD

**Issue by tekkac** [cienicera/cairo-wave#9]
**Contributing**
---
- Go to the [Nicera Labs OD Telegram](https://t.me/niceralabs)
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Description**
---
Implement a sine wave generator.

**Additional Information**
---------------------------
[Medium Difficulty  - Cairo - Medium Priority]

**Acceptance Criteria**
---

- [ ] The `generate_sine_wave` is implemented
- [ ] Write and pass unit tests
- [ ] Generate example files

**Comment by Oshioke-Salaki** [comment]
Please can I handle this?

**Comment by tekkac** [comment]
Please join the Telegram in the description so we can have a quick chat about it.
